<h1>Numpy</h1>

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
k=[23,3,34,54,56,5,66,45]

In [6]:
m=np.array(k)
m

array([23,  3, 34, 54, 56,  5, 66, 45])

In [7]:
m+1

array([24,  4, 35, 55, 57,  6, 67, 46])

In [8]:
m.dtype

dtype('int32')

In [9]:
m.ndim

1

In [10]:
m.shape

(8,)

In [12]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
f1=[[1,2,3],[4,5,6],[7,8,9]]
arr1=np.array(f1)

In [17]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr1.ndim

2

In [19]:
arr1.shape

(3, 3)

In [20]:
arr1.dtype

dtype('int32')

In [21]:
#zero matrix

In [22]:
np.zeros(4)

array([0., 0., 0., 0.])

In [23]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
np.diag((1,2,3,4))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [27]:
#indexing

In [28]:
import random

In [29]:
random.randint(1,12)

9

In [31]:
np.random.randint(1,100)

60

In [32]:
np.random.randint(1,100,(4,5))

array([[60, 26, 17, 75,  1],
       [65, 94, 56, 70, 19],
       [98, 43, 22, 37, 56],
       [27, 68, 63, 68, 54]])

In [34]:
arr2=np.random.randint(1,30,(6,6))

In [35]:
arr2

array([[28,  1,  1, 22, 21, 16],
       [ 7, 22,  4,  7, 25,  6],
       [18,  8,  4, 21,  5,  5],
       [10, 20, 27, 12,  7, 12],
       [28,  7,  6, 10, 17,  5],
       [14, 12,  3, 19, 25,  4]])

In [36]:
arr2.shape

(6, 6)

In [37]:
arr2.ndim

2

In [39]:
arr2[0]

array([28,  1,  1, 22, 21, 16])

In [40]:
arr2

array([[28,  1,  1, 22, 21, 16],
       [ 7, 22,  4,  7, 25,  6],
       [18,  8,  4, 21,  5,  5],
       [10, 20, 27, 12,  7, 12],
       [28,  7,  6, 10, 17,  5],
       [14, 12,  3, 19, 25,  4]])

In [41]:
arr2[2]

array([18,  8,  4, 21,  5,  5])

In [42]:
arr2[(1,1)]

22

In [43]:
arr2[(2,2)]

4

In [44]:
arr2[:,0]

array([28,  7, 18, 10, 28, 14])

In [45]:
arr2[-1]

array([14, 12,  3, 19, 25,  4])

In [46]:
arr2[:,2]

array([ 1,  4,  4, 27,  6,  3])

In [47]:
arr2[3]

array([10, 20, 27, 12,  7, 12])

In [48]:
arr2[4]

array([28,  7,  6, 10, 17,  5])

In [49]:
arr2

array([[28,  1,  1, 22, 21, 16],
       [ 7, 22,  4,  7, 25,  6],
       [18,  8,  4, 21,  5,  5],
       [10, 20, 27, 12,  7, 12],
       [28,  7,  6, 10, 17,  5],
       [14, 12,  3, 19, 25,  4]])

In [50]:
arr2[:2,]

array([[28,  1,  1, 22, 21, 16],
       [ 7, 22,  4,  7, 25,  6]])

In [51]:
arr2[:,2]

array([ 1,  4,  4, 27,  6,  3])

In [55]:
arr2[1:3,1:3]

array([[22,  4],
       [ 8,  4]])

In [75]:
arr2[-3:-1,-4:-2]

array([[27, 12],
       [ 6, 10]])

In [78]:
arr3=np.random.randint(1,50,(6,8))
arr3

array([[49, 45, 32, 21,  1, 10, 15, 18],
       [23, 19,  4, 13, 38, 48,  1,  2],
       [ 4,  1, 23, 26, 13, 15, 18, 37],
       [40, 36,  6,  1, 15,  5,  6, 20],
       [25, 40, 23, 15, 40,  2,  2, 39],
       [35, 37, 39, 29, 17, 37,  3, 30]])

In [81]:
arr3[2:5,2:5]=0

In [82]:
arr3

array([[49, 45, 32, 21,  1, 10, 15, 18],
       [23, 19,  4, 13, 38, 48,  1,  2],
       [ 4,  1,  0,  0,  0, 15, 18, 37],
       [40, 36,  0,  0,  0,  5,  6, 20],
       [25, 40,  0,  0,  0,  2,  2, 39],
       [35, 37, 39, 29, 17, 37,  3, 30]])

In [83]:
arr3

array([[49, 45, 32, 21,  1, 10, 15, 18],
       [23, 19,  4, 13, 38, 48,  1,  2],
       [ 4,  1,  0,  0,  0, 15, 18, 37],
       [40, 36,  0,  0,  0,  5,  6, 20],
       [25, 40,  0,  0,  0,  2,  2, 39],
       [35, 37, 39, 29, 17, 37,  3, 30]])

In [85]:
arr3[-4:-1,-3:-1]

array([[15, 18],
       [ 5,  6],
       [ 2,  2]])

In [89]:
arr3[-2:,0:2]=56

In [90]:
arr3

array([[49, 45, 32, 21,  1, 10, 15, 18],
       [23, 19,  4, 13, 38, 48,  1,  2],
       [ 4,  1,  0,  0,  0, 15, 18, 37],
       [40, 36,  0,  0,  0,  5,  6, 20],
       [56, 56,  0,  0,  0,  2,  2, 39],
       [56, 56, 39, 29, 17, 37,  3, 30]])

In [91]:
arr=np.random.randint(1,100,(8,7))
arr

array([[94, 85, 53, 59, 80, 16, 26],
       [44, 93, 75, 85, 76, 47, 28],
       [53,  7, 80, 34,  5, 25, 52],
       [74, 76, 48, 24, 88, 30, 48],
       [75, 87, 69, 62, 15, 87, 45],
       [99, 60, 97, 33, 66, 74, 44],
       [32, 40, 55, 48, 42, 45, 20],
       [55, 64, 70, 16, 15, 40, 80]])

In [92]:
arr>70

array([[ True,  True, False, False,  True, False, False],
       [False,  True,  True,  True,  True, False, False],
       [False, False,  True, False, False, False, False],
       [ True,  True, False, False,  True, False, False],
       [ True,  True, False, False, False,  True, False],
       [ True, False,  True, False, False,  True, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False,  True]])

In [93]:
mask=arr>70

In [96]:
arr[~mask]

array([53, 59, 16, 26, 44, 47, 28, 53,  7, 34,  5, 25, 52, 48, 24, 30, 48,
       69, 62, 15, 45, 60, 33, 66, 44, 32, 40, 55, 48, 42, 45, 20, 55, 64,
       70, 16, 15, 40])

In [97]:
arr>70

array([[ True,  True, False, False,  True, False, False],
       [False,  True,  True,  True,  True, False, False],
       [False, False,  True, False, False, False, False],
       [ True,  True, False, False,  True, False, False],
       [ True,  True, False, False, False,  True, False],
       [ True, False,  True, False, False,  True, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False,  True]])

In [101]:
arr[arr>70]

array([94, 85, 80, 93, 75, 85, 76, 80, 74, 76, 88, 75, 87, 87, 99, 97, 74,
       80])

In [103]:
arr[~(arr>70)]

array([53, 59, 16, 26, 44, 47, 28, 53,  7, 34,  5, 25, 52, 48, 24, 30, 48,
       69, 62, 15, 45, 60, 33, 66, 44, 32, 40, 55, 48, 42, 45, 20, 55, 64,
       70, 16, 15, 40])

In [104]:
arr

array([[94, 85, 53, 59, 80, 16, 26],
       [44, 93, 75, 85, 76, 47, 28],
       [53,  7, 80, 34,  5, 25, 52],
       [74, 76, 48, 24, 88, 30, 48],
       [75, 87, 69, 62, 15, 87, 45],
       [99, 60, 97, 33, 66, 74, 44],
       [32, 40, 55, 48, 42, 45, 20],
       [55, 64, 70, 16, 15, 40, 80]])

In [110]:
m=arr[0]>50
m

array([ True,  True,  True,  True,  True, False, False])

In [114]:
arr[0][arr[0]>50]

array([94, 85, 53, 59, 80])

In [116]:
arr[0][~(arr[0]>50)]

array([16, 26])

In [117]:
#sum

In [118]:
arr

array([[94, 85, 53, 59, 80, 16, 26],
       [44, 93, 75, 85, 76, 47, 28],
       [53,  7, 80, 34,  5, 25, 52],
       [74, 76, 48, 24, 88, 30, 48],
       [75, 87, 69, 62, 15, 87, 45],
       [99, 60, 97, 33, 66, 74, 44],
       [32, 40, 55, 48, 42, 45, 20],
       [55, 64, 70, 16, 15, 40, 80]])

In [119]:
arr>60

array([[ True,  True, False, False,  True, False, False],
       [False,  True,  True,  True,  True, False, False],
       [False, False,  True, False, False, False, False],
       [ True,  True, False, False,  True, False, False],
       [ True,  True,  True,  True, False,  True, False],
       [ True, False,  True, False,  True,  True, False],
       [False, False, False, False, False, False, False],
       [False,  True,  True, False, False, False,  True]])

In [120]:
arr[arr>60]

array([94, 85, 80, 93, 75, 85, 76, 80, 74, 76, 88, 75, 87, 69, 62, 87, 99,
       97, 66, 74, 64, 70, 80])

In [122]:
np.sum(arr>60)

23

In [125]:
np.sum(arr[arr>60])

1836

In [126]:
arr

array([[94, 85, 53, 59, 80, 16, 26],
       [44, 93, 75, 85, 76, 47, 28],
       [53,  7, 80, 34,  5, 25, 52],
       [74, 76, 48, 24, 88, 30, 48],
       [75, 87, 69, 62, 15, 87, 45],
       [99, 60, 97, 33, 66, 74, 44],
       [32, 40, 55, 48, 42, 45, 20],
       [55, 64, 70, 16, 15, 40, 80]])

In [135]:
np.sum(arr[2]>50)

3

In [129]:
arr[2][arr[2]>50]

array([53, 80, 52])

In [130]:
arr[2][~(arr[2]>50)]

array([ 7, 34,  5, 25])

In [134]:
np.sum(arr[2][arr[2]>30])

219

In [136]:
arr

array([[94, 85, 53, 59, 80, 16, 26],
       [44, 93, 75, 85, 76, 47, 28],
       [53,  7, 80, 34,  5, 25, 52],
       [74, 76, 48, 24, 88, 30, 48],
       [75, 87, 69, 62, 15, 87, 45],
       [99, 60, 97, 33, 66, 74, 44],
       [32, 40, 55, 48, 42, 45, 20],
       [55, 64, 70, 16, 15, 40, 80]])

In [138]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [140]:
b=np.arange(1,10,2)
b

array([1, 3, 5, 7, 9])

In [141]:
a+b

array([ 2,  5,  8, 11, 14])

In [142]:
a-b

array([ 0, -1, -2, -3, -4])

In [143]:
a*b

array([ 1,  6, 15, 28, 45])

In [144]:
a/b

array([1.        , 0.66666667, 0.6       , 0.57142857, 0.55555556])

In [145]:
a**b

array([      1,       8,     243,   16384, 1953125])

In [146]:
a%b

array([0, 2, 3, 4, 5])

In [147]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [148]:
np.cos(b)

array([ 0.54030231, -0.9899925 ,  0.28366219,  0.75390225, -0.91113026])

In [149]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [150]:
np.longlong(b)

array([1, 3, 5, 7, 9], dtype=int64)

In [153]:
x=np.random.randint(1,50,(3,5))
x

array([[27, 16, 11, 15,  4],
       [34, 15, 42,  5,  5],
       [38, 48, 18, 37, 15]])

In [171]:
y=np.random.randint(1,50,(5,6))
y

array([[45, 28, 30, 46, 16,  2],
       [44, 11, 37, 24,  1,  4],
       [37,  6,  5, 10, 49, 18],
       [ 6,  3, 33, 29, 43,  2],
       [49, 25, 19,  1, 12, 43]])

In [172]:
np.dot(x,y)

array([[2612, 1143, 2028, 2175, 1680,  518],
       [4019, 1509, 2045, 2494, 2892, 1109],
       [5445, 2186, 4512, 4168, 3309, 1311]])

In [174]:
c=np.arange(1,100,5)
c

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [181]:
x=np.reshape(c,(5,4))
x

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56],
       [61, 66, 71, 76],
       [81, 86, 91, 96]])

In [192]:
x.flatten()

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [193]:
np.sqrt(y)

array([1.        , 2.44948974, 3.31662479, 4.        , 4.58257569,
       5.09901951, 5.56776436, 6.        , 6.40312424, 6.78232998,
       7.14142843, 7.48331477, 7.81024968, 8.1240384 , 8.42614977,
       8.71779789, 9.        , 9.2736185 , 9.53939201, 9.79795897])

In [194]:
np.sqrt(x)

array([1.        , 2.44948974, 3.31662479, 4.        , 4.58257569,
       5.09901951, 5.56776436, 6.        , 6.40312424, 6.78232998,
       7.14142843, 7.48331477, 7.81024968, 8.1240384 , 8.42614977,
       8.71779789, 9.        , 9.2736185 , 9.53939201, 9.79795897])

In [196]:
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [203]:
y=np.reshape(x,(4,5))

In [204]:
np.sum(y)

970

In [205]:
np.sum(y,0)

array([154, 174, 194, 214, 234])

In [207]:
np.sum(y,axis=1)

array([ 55, 180, 305, 430])

In [208]:
y

array([[ 1,  6, 11, 16, 21],
       [26, 31, 36, 41, 46],
       [51, 56, 61, 66, 71],
       [76, 81, 86, 91, 96]])

In [209]:
np.min(y)

1

In [210]:
np.max(y)

96

In [211]:
np.max(y,1)

array([21, 46, 71, 96])

In [212]:
np.max(y, axis=1)

array([21, 46, 71, 96])

In [213]:
np.min(y,0)

array([ 1,  6, 11, 16, 21])

In [214]:
np.std(y)

28.83140648667699

In [215]:
np.std(y,axis=0)

array([27.95084972, 27.95084972, 27.95084972, 27.95084972, 27.95084972])

In [216]:
np.std(y,axis=1)

array([7.07106781, 7.07106781, 7.07106781, 7.07106781])

In [217]:
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [218]:
np.mean(x)

48.5

In [219]:
np.mean([1,2,3])

2.0

In [220]:
y


array([[ 1,  6, 11, 16, 21],
       [26, 31, 36, 41, 46],
       [51, 56, 61, 66, 71],
       [76, 81, 86, 91, 96]])

In [221]:
np.transpose(y)

array([[ 1, 26, 51, 76],
       [ 6, 31, 56, 81],
       [11, 36, 61, 86],
       [16, 41, 66, 91],
       [21, 46, 71, 96]])

In [223]:
x=np.random.randint(1,50,(4,5))
x

array([[21, 29, 19, 43, 24],
       [43, 20, 18, 16, 24],
       [12, 38, 49, 45, 20],
       [17, 48, 31, 13, 41]])

In [233]:
y=np.random.randint(1,50,(4,5))
y

array([[15, 40, 16, 28, 34],
       [30, 45, 28, 31, 29],
       [42, 19,  3, 16, 34],
       [36, 17, 44, 47, 24]])

In [234]:
np.hstack((x,y))

array([[21, 29, 19, 43, 24, 15, 40, 16, 28, 34],
       [43, 20, 18, 16, 24, 30, 45, 28, 31, 29],
       [12, 38, 49, 45, 20, 42, 19,  3, 16, 34],
       [17, 48, 31, 13, 41, 36, 17, 44, 47, 24]])

In [236]:
a=np.random.randint(1,45,(5,5))
a

array([[26, 12, 38, 22, 15],
       [42, 42,  6, 32, 12],
       [19, 24, 20, 33,  2],
       [37, 39, 44, 33, 22],
       [ 9, 19, 18, 34, 38]])

In [239]:
b=np.random.randint(1,34,(5,5))
b

array([[29, 19, 15, 20, 12],
       [25, 32, 24, 22, 20],
       [18,  1, 25, 15,  6],
       [ 6, 18, 26, 19, 22],
       [ 5, 30, 32, 14, 13]])

In [240]:
np.vstack((a,b))

array([[26, 12, 38, 22, 15],
       [42, 42,  6, 32, 12],
       [19, 24, 20, 33,  2],
       [37, 39, 44, 33, 22],
       [ 9, 19, 18, 34, 38],
       [29, 19, 15, 20, 12],
       [25, 32, 24, 22, 20],
       [18,  1, 25, 15,  6],
       [ 6, 18, 26, 19, 22],
       [ 5, 30, 32, 14, 13]])

In [241]:
#broadcasting

In [242]:
z=np.random.randint(2,45, size=(5,6))
z

array([[32, 44, 12, 37, 12, 11],
       [ 6, 14, 16, 43, 25, 35],
       [ 5,  8, 29, 12, 23, 35],
       [14, 34, 16,  8, 34, 18],
       [44,  6, 15, 29, 31,  4]])

In [250]:
d=np.array([2,2,3,4,5,6])
d

array([2, 2, 3, 4, 5, 6])

In [248]:
z.shape

(5, 6)

In [251]:
d.shape

(6,)

In [252]:
z+d

array([[34, 46, 15, 41, 17, 17],
       [ 8, 16, 19, 47, 30, 41],
       [ 7, 10, 32, 16, 28, 41],
       [16, 36, 19, 12, 39, 24],
       [46,  8, 18, 33, 36, 10]])

In [253]:
d+z

array([[34, 46, 15, 41, 17, 17],
       [ 8, 16, 19, 47, 30, 41],
       [ 7, 10, 32, 16, 28, 41],
       [16, 36, 19, 12, 39, 24],
       [46,  8, 18, 33, 36, 10]])

In [254]:
a=[1,2,3,4,4,55,66,66,6]

In [255]:
b=[3,4,5,6,77,4,333,32,2]

In [257]:
c=np.array(a)
c

array([ 1,  2,  3,  4,  4, 55, 66, 66,  6])

In [260]:
d=np.array(b)
d

array([  3,   4,   5,   6,  77,   4, 333,  32,   2])

In [264]:
np.sqrt(np.sum(np.square(d-c)))

283.56128085477394

In [317]:
a=[2,3,4,5,56,6,6]
b=[3,45,6,6,67,45,4]
c=[3,4,5,6,7,7,8]
arr=np.array([a,b,c])
arr

array([[ 2,  3,  4,  5, 56,  6,  6],
       [ 3, 45,  6,  6, 67, 45,  4],
       [ 3,  4,  5,  6,  7,  7,  8]])

In [334]:
arr[:,1]

array([ 3, 45,  4])

In [348]:
arr[1:,5:]

array([[45,  4],
       [ 7,  8]])

In [318]:
a

[2, 3, 4, 5, 56, 6, 6]

In [319]:
type(a)

list

In [325]:
a1=np.array(a)

In [331]:
a1[:-1]

array([ 2,  3,  4,  5, 56,  6])

In [327]:
type(a1)

numpy.ndarray

In [332]:
a1[::-1]

array([ 6,  6, 56,  5,  4,  3,  2])

In [349]:
a1[::-2]

array([ 6, 56,  4,  2])

<h1>pandas</h1>

#pandas:----------------------------------->dataframe

In [276]:
st=['html','excel','python','power_bi','machine_learning','sql']

In [277]:
st

['html', 'excel', 'python', 'power_bi', 'machine_learning', 'sql']

In [281]:
import pandas as pd

In [283]:
d=pd.Series(st)
d

0                html
1               excel
2              python
3            power_bi
4    machine_learning
5                 sql
dtype: object

In [285]:
d[3]

'power_bi'

In [290]:
d.index=['a','b','c','d','e','f']

In [291]:
d

a                html
b               excel
c              python
d            power_bi
e    machine_learning
f                 sql
dtype: object

In [292]:
d['f']

'sql'

In [293]:
d[-3]

C:\Users\DELL\AppData\Local\Temp\ipykernel_16864\1062201034.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  d[-3]


'power_bi'

In [294]:
arr1=np.random.randint(1,100,(56,45))

In [295]:
arr1

array([[83, 64, 65, ..., 64, 36, 86],
       [11, 58, 40, ..., 70,  7, 21],
       [78, 44, 26, ..., 66, 94, 81],
       ...,
       [97, 97,  9, ..., 73, 48, 66],
       [51, 26, 53, ..., 65, 31,  9],
       [56, 86, 59, ..., 98, 10, 72]])

In [297]:
arr=pd.DataFrame(arr1)

In [298]:
arr

0   1   2   3   4   5   6   7   8   9   ...  35  36  37  38  39  40  41  \
0   83  64  65  21  76  73  67  74  13  83  ...  19  20   2  99  32  61  58   
1   11  58  40  43  30  46  61  72  51  70  ...  50  67  14  64  15  99  73   
2   78  44  26  88   7  46  12  59  51   3  ...  84  71  52  48  77  61   9   
3   14  24  71  99  42  67  65  24  94  23  ...  23   7  33  26  96  24  13   
4   10   8  82  75  62  75  26  32  28  41  ...  95  88  94  89  37  34  36   
5   75  96  78  94  99  97  26  97  15  69  ...  28  80  52  85  83  22   2   
6   36  54  48  10  71   9  69  47  89  88  ...  99  21   6   4  52  18  42   
7   20  63   9  38  40  30  16  92  69  62  ...  44  49  22  34  92   9  55   
8   60  24  50  33  96  43  34  76  13  51  ...  93  76  83  71  20  37  96   
9   44  66  64  23  23  32  46  22  37  70  ...   3  15  56  86  89  90  64   
10  73   5  51  96  77  38  71  44  99  25  ...  33  85  29  44  48  63   3   
11  72  44  49  72  20  57  37  70  58  17  ...  53  15  25   8  80  43  55   
12  82  21  64  68  38  48  70  38  75  44  ...  59  27  22  23  45  27  84   
13  56  85  38  34  40  53  99  92   7  74  ...  89  72  66  57   3  83  51   
14  55  10  93  44   7  37  88  57  35  46  ...   8  97   8  61  29  50  87   
15  69  58  67  27  88  55   6  57  56  26  ...  41   2  25  10  29  72  87   
16  27  41   2  30  19  39  71  70  92   9  ...  84  52  46  74  35  61  85   
17  19  56  96  98  24  42  35  11  68  53  ...  21  33  71  48  65   1   7   
18  19  41  68  65  66  89   5  68  94  23  ...  82  95   5   9  42  33  50   
19  11   9  82  44  51  86  12   4  61  60  ...  11  12  86  87  17  15  40   
20  60  82  20  95  32   8  92  81  18  47  ...  24   1  85   3  84  11  93   
21  81  70  60  37  92  52  77  71  19  74  ...  64  54  39   7   3  47  70   
22  97   9  53  17  95  11  50  56  16  24  ...  20  21  54  67   7  45  30   
23  16  15  75  51  86  73  34  26  24  28  ...  86  34  31  13  59  73  22   
24  35  90  37  84  79  99  68  26  93  38  ...  92  64  16  48  25  98  44   
25  60  44  33  20  27  32  60  70  25  58  ...  17  13  63  64  56  66  70   
26  28  97  73  45  60  84  32  23  53  20  ...  23  64  36  89  83  55  75   
27  30  35  43  80  99   4  26  54  72   7  ...  82  42  69  15  51   5  89   
28  33  38  20  72  72  37  76  10  75   8  ...  33  69  52  85  53  58  74   
29  17  25   8  81  17  75  59  45  16  57  ...  67   2  25   1  55  46  65   
30  67  22  69  12   9  92   4  12  65  88  ...  76  39  21  50  26  89  19   
31  52  74  15  78  49  71  50  39  88  63  ...  49  41  59  29  30  15  88   
32  15  19  31  82  51  38   5  46   8  95  ...  87   5  51  37  39  91  93   
33   4  23  44  49   3  99  67  69  82  64  ...   1  47  54  17  15  52  19   
34  53  91  17  89  14  75  24  80  31  73  ...  93  19  53  68  89  46  41   
35   9  44  63  93  26   4  64  23  17  40  ...  29  15  30   5  47  68  61   
36  28  91  72  84  65  72   1  89  64  80  ...  19  57  92   3  37  27   5   
37  49  31  81  80  58  62  41  85  44  34  ...   3  92  72   4  48  79   3   
38  90  82  24  75  35  96  62  45   1  43  ...   8  43  61  30  67  94  79   
39  42  42  54  31  84   6  79  56  90  55  ...   9  63  73  66  79  36  37   
40  73  53  53  82  47  32  58  37  38  74  ...  77  38  46  44  69  20  53   
41  11  54  94  97  38  97  60  94  14  27  ...  52  77  12  69  79  27  88   
42  26  89  45  62  72   9  94  63  17  71  ...  17  68  86  86  84  86  47   
43  56  42  79  66  72  24  87  80  88  51  ...  24  14  46  24  22  71  85   
44  18  90  70  32   2  67  78  52  59  96  ...  66  35  31  78   7  89  92   
45  25  50  22  43  42  24   2  46  70  89  ...  55  60  98   2  69  47   7   
46  11  43  66  11  67  97  35  35  24  96  ...  57  98  56  62  90  18  72   
47  47  26  46  53  20  96  16  58  88  36  ...  58  11  54  85  42  64  36   
48  52  91  39   8  49  78  52  88  41  46  ...  23  28  62  47  84  92  95   
49  48  90  82  64  18  91  15  97   2  90  ...  80  8

In [299]:
arr[2]

0     65
1     40
2     26
3     71
4     82
5     78
6     48
7      9
8     50
9     64
10    51
11    49
12    64
13    38
14    93
15    67
16     2
17    96
18    68
19    82
20    20
21    60
22    53
23    75
24    37
25    33
26    73
27    43
28    20
29     8
30    69
31    15
32    31
33    44
34    17
35    63
36    72
37    81
38    24
39    54
40    53
41    94
42    45
43    79
44    70
45    22
46    66
47    46
48    39
49    82
50    14
51    80
52    61
53     9
54    53
55    59
Name: 2, dtype: int32

In [300]:
arr

0   1   2   3   4   5   6   7   8   9   ...  35  36  37  38  39  40  41  \
0   83  64  65  21  76  73  67  74  13  83  ...  19  20   2  99  32  61  58   
1   11  58  40  43  30  46  61  72  51  70  ...  50  67  14  64  15  99  73   
2   78  44  26  88   7  46  12  59  51   3  ...  84  71  52  48  77  61   9   
3   14  24  71  99  42  67  65  24  94  23  ...  23   7  33  26  96  24  13   
4   10   8  82  75  62  75  26  32  28  41  ...  95  88  94  89  37  34  36   
5   75  96  78  94  99  97  26  97  15  69  ...  28  80  52  85  83  22   2   
6   36  54  48  10  71   9  69  47  89  88  ...  99  21   6   4  52  18  42   
7   20  63   9  38  40  30  16  92  69  62  ...  44  49  22  34  92   9  55   
8   60  24  50  33  96  43  34  76  13  51  ...  93  76  83  71  20  37  96   
9   44  66  64  23  23  32  46  22  37  70  ...   3  15  56  86  89  90  64   
10  73   5  51  96  77  38  71  44  99  25  ...  33  85  29  44  48  63   3   
11  72  44  49  72  20  57  37  70  58  17  ...  53  15  25   8  80  43  55   
12  82  21  64  68  38  48  70  38  75  44  ...  59  27  22  23  45  27  84   
13  56  85  38  34  40  53  99  92   7  74  ...  89  72  66  57   3  83  51   
14  55  10  93  44   7  37  88  57  35  46  ...   8  97   8  61  29  50  87   
15  69  58  67  27  88  55   6  57  56  26  ...  41   2  25  10  29  72  87   
16  27  41   2  30  19  39  71  70  92   9  ...  84  52  46  74  35  61  85   
17  19  56  96  98  24  42  35  11  68  53  ...  21  33  71  48  65   1   7   
18  19  41  68  65  66  89   5  68  94  23  ...  82  95   5   9  42  33  50   
19  11   9  82  44  51  86  12   4  61  60  ...  11  12  86  87  17  15  40   
20  60  82  20  95  32   8  92  81  18  47  ...  24   1  85   3  84  11  93   
21  81  70  60  37  92  52  77  71  19  74  ...  64  54  39   7   3  47  70   
22  97   9  53  17  95  11  50  56  16  24  ...  20  21  54  67   7  45  30   
23  16  15  75  51  86  73  34  26  24  28  ...  86  34  31  13  59  73  22   
24  35  90  37  84  79  99  68  26  93  38  ...  92  64  16  48  25  98  44   
25  60  44  33  20  27  32  60  70  25  58  ...  17  13  63  64  56  66  70   
26  28  97  73  45  60  84  32  23  53  20  ...  23  64  36  89  83  55  75   
27  30  35  43  80  99   4  26  54  72   7  ...  82  42  69  15  51   5  89   
28  33  38  20  72  72  37  76  10  75   8  ...  33  69  52  85  53  58  74   
29  17  25   8  81  17  75  59  45  16  57  ...  67   2  25   1  55  46  65   
30  67  22  69  12   9  92   4  12  65  88  ...  76  39  21  50  26  89  19   
31  52  74  15  78  49  71  50  39  88  63  ...  49  41  59  29  30  15  88   
32  15  19  31  82  51  38   5  46   8  95  ...  87   5  51  37  39  91  93   
33   4  23  44  49   3  99  67  69  82  64  ...   1  47  54  17  15  52  19   
34  53  91  17  89  14  75  24  80  31  73  ...  93  19  53  68  89  46  41   
35   9  44  63  93  26   4  64  23  17  40  ...  29  15  30   5  47  68  61   
36  28  91  72  84  65  72   1  89  64  80  ...  19  57  92   3  37  27   5   
37  49  31  81  80  58  62  41  85  44  34  ...   3  92  72   4  48  79   3   
38  90  82  24  75  35  96  62  45   1  43  ...   8  43  61  30  67  94  79   
39  42  42  54  31  84   6  79  56  90  55  ...   9  63  73  66  79  36  37   
40  73  53  53  82  47  32  58  37  38  74  ...  77  38  46  44  69  20  53   
41  11  54  94  97  38  97  60  94  14  27  ...  52  77  12  69  79  27  88   
42  26  89  45  62  72   9  94  63  17  71  ...  17  68  86  86  84  86  47   
43  56  42  79  66  72  24  87  80  88  51  ...  24  14  46  24  22  71  85   
44  18  90  70  32   2  67  78  52  59  96  ...  66  35  31  78   7  89  92   
45  25  50  22  43  42  24   2  46  70  89  ...  55  60  98   2  69  47   7   
46  11  43  66  11  67  97  35  35  24  96  ...  57  98  56  62  90  18  72   
47  47  26  46  53  20  96  16  58  88  36  ...  58  11  54  85  42  64  36   
48  52  91  39   8  49  78  52  88  41  46  ...  23  28  62  47  84  92  95   
49  48  90  82  64  18  91  15  97   2  90  ...  80  8

In [301]:
arr.index

RangeIndex(start=0, stop=56, step=1)

In [302]:
arr.shape

(56, 45)

In [303]:
arr.ndim

2

In [309]:
arr.iloc(0)

In [310]:
a=np.random.randint(1,50,(4,8))
a

array([[21, 32, 25,  7, 18,  3, 42, 44],
       [11, 49, 43, 33, 41, 15, 49, 31],
       [23, 41, 21,  3, 14, 24, 46, 26],
       [ 5, 48, 10, 13, 40, 32, 20, 47]])

In [311]:
d=pd.DataFrame(a)
d

0   1   2   3   4   5   6   7
0  21  32  25   7  18   3  42  44
1  11  49  43  33  41  15  49  31
2  23  41  21   3  14  24  46  26
3   5  48  10  13  40  32  20  47

In [314]:
d.iloc[1]

0    11
1    49
2    43
3    33
4    41
5    15
6    49
7    31
Name: 1, dtype: int32

In [313]:
d.loc[0]

0    21
1    32
2    25
3     7
4    18
5     3
6    42
7    44
Name: 0, dtype: int32

In [315]:
d.loc[3]

0     5
1    48
2    10
3    13
4    40
5    32
6    20
7    47
Name: 3, dtype: int32