Numpy: numerical python<br>
it is used for performing all types of mathematical/numerical<br>
or scientific calculation<br>
numpy uses array: arrays means vectors or metrics of linear algerbra<br>
it supports 1,2, or more than 2 dimentional arrays.<br>
arrays are homogeneous in nature<br>

## Numpy
NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

## What is an array
An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [13]:
import numpy as np


vertorization: performing fast operations

In [3]:
k=[1,2,3,4,5,5]

In [4]:
p=[]
for i in k:
    print(i+1)

2
3
4
5
6
6


In [5]:
p=[]
for i in k:
    p.append(i+1)

In [6]:
p

[2, 3, 4, 5, 6, 6]

In [11]:
%timeit [i+1 for i in k]

260 ns ± 27 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [12]:
p

[2, 3, 4, 5, 6, 6]

In [13]:
arr=np.array(p)

In [14]:
arr

array([2, 3, 4, 5, 6, 6])

In [21]:
type(arr)

numpy.ndarray

In [22]:
%timeit arr+1

1.17 µs ± 52.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


numpy basics<br>
np.arrays<br>
np.arange<br>

In [23]:
w=[6,7,8,9,3,4,5]
arr=np.array(w)

In [24]:
arr

array([6, 7, 8, 9, 3, 4, 5])

In [25]:
type(arr)

numpy.ndarray

In [26]:
arr.ndim

1

In [34]:
s=[[1,2,3],[4,5,6],[3,4,5]]
arr2=np.array(s)

In [35]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [3, 4, 5]])

In [36]:
arr2.ndim

2

In [37]:
arr2.shape

(3, 3)

In [41]:
a=list(range(1,10))
a

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [44]:
arr4=np.arange(1,21,2)
arr4

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

some more special arrays

In [45]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [46]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [48]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [49]:
np.ones(1)

array([1.])

In [50]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [51]:
np.diag([2,3])

array([[2, 0],
       [0, 3]])

In [52]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
np.identity((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
np.diag([3,4,5])

array([[3, 0, 0],
       [0, 4, 0],
       [0, 0, 5]])

In [56]:
#indexing
import random

In [58]:
random.randint(1,10)

7

In [59]:
np.random.randint(100)

55

In [61]:
arr= np.random.randint(1,100,(8,6))
arr

array([[81, 30,  7, 57, 65, 68],
       [13,  6, 80, 62, 35, 73],
       [62, 13, 65, 43, 13, 50],
       [11, 28, 59, 78, 97, 17],
       [94,  4, 26, 99, 38, 86],
       [94, 27, 72, 10,  1, 56],
       [51, 57, 32, 16, 63, 86],
       [99, 26, 17, 58, 64, 14]])

In [4]:
arr4=np.random.randint(1,100,(3,4))
arr4

array([[58, 38, 68, 19],
       [63, 74, 44, 36],
       [10, 62, 32, 61]])

In [6]:
arr4[:,1]

array([38, 74, 62])

In [7]:
#masking: boolean indexing: 

In [9]:
arr4>50

array([[ True, False,  True, False],
       [ True,  True, False, False],
       [False,  True, False,  True]])

In [10]:
# verisation:


In [11]:
a=[1,2,4,7,-2,9,6,0]
b=[5,5,8,2,-9,2,1,6]

In [18]:
a1=np.array(a)
b2=np.array(b)

In [19]:
print(a1)
print(b2)

[ 1  2  4  7 -2  9  6  0]
[ 5  5  8  2 -9  2  1  6]


In [20]:
temp= a1-b2

In [23]:
a3=temp**2

In [26]:
np.sqrt(a3)

array([4., 3., 4., 5., 7., 7., 5., 6.])

In [30]:
a1=np.array(a)
b2=np.array(b)

In [32]:
np.sqrt(np.sum(np.square(a1-b2)))

15.0

In [1]:
#indexing

In [5]:
a=np.random.randint(1,50,(4,5))
a

array([[42, 20, 17, 27, 34],
       [45, 43, 24, 14, 47],
       [13, 22, 38, 22, 22],
       [34, 18,  9, 39, 21]])

In [7]:
a[:,0]

array([42, 45, 13, 34])

In [11]:
a[2:,:2]

array([[13, 22],
       [34, 18]])